# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:30:38+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from pydantic import conint

from models import (
    ApiArticlesGetResponse,
    ApiArticlesIdGetResponse,
    ApiArticlesLatestGetResponse,
    ApiArticlesMeAllGetResponse,
    ApiArticlesMeGetResponse,
    ApiArticlesMePublishedGetResponse,
    ApiArticlesMeUnpublishedGetResponse,
    ApiArticlesUsernameSlugGetResponse,
    ApiCommentsGetResponse,
    ApiDisplayAdsIdPutRequest,
    ApiDisplayAdsPostRequest,
    ApiFollowersUsersGetResponse,
    ApiFollowsTagsGetResponse,
    ApiOrganizationsUsernameArticlesGetResponse,
    ApiOrganizationsUsernameGetResponse,
    ApiOrganizationsUsernameUsersGetResponse,
    ApiPagesGetResponse,
    ApiPagesPostRequest,
    ApiPodcastEpisodesGetResponse,
    ApiProfileImagesUsernameGetResponse,
    ApiReadinglistGetResponse,
    ApiTagsGetResponse,
    ApiUsersIdGetResponse,
    ApiUsersMeGetResponse,
    ApiVideosGetResponse,
    Article,
    Category,
    Page,
    ReactableType,
    State,
    UserInviteParam,
)

app = MCPProxy(
    description="Access Forem articles, users and other resources via API.\n        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).\n        All endpoints can be accessed with the 'api-key' header and a accept header, but\n        some of them are accessible publicly without authentication.\n\n        Dates and date times, unless otherwise specified, must be in\n        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.",
    title='Forem API V1',
    version='1.0.0',
    servers=[{'description': 'Production server', 'url': 'https://dev.to/api'}],
)


@app.post(
    '/api/admin/users',
    description=""" This endpoint allows the client to trigger an invitation to the provided email address.

        It requires a token from a user with `super_admin` privileges. """,
    tags=['user_management', 'user_account_moderation'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def post_admin_users_create(body: UserInviteParam = None):
    """
    Invite a User
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/articles',
    description=""" This endpoint allows the client to retrieve a list of articles.

"Articles" are all the posts that users create on DEV that typically
show up in the feed. They can be a blog post, a discussion question,
a help thread etc. but is referred to as article within the code.

By default it will return featured, published articles ordered
by descending popularity.

It supports pagination, each page will contain `30` articles by default. """,
    tags=['article_management'],
)
def get_articles(
    page: Optional[conint(ge=1)] = 1,
    per_page: Optional[conint(ge=1, le=1000)] = 30,
    tag: Optional[str] = None,
    tags: Optional[str] = None,
    tags_exclude: Optional[str] = None,
    username: Optional[str] = None,
    state: Optional[State] = None,
    top: Optional[conint(ge=1)] = None,
    collection_id: Optional[int] = None,
):
    """
    Published articles
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/articles',
    description=""" This endpoint allows the client to create a new article.

"Articles" are all the posts that users create on DEV that typically show up in the feed. They can be a blog post, a discussion question, a help thread etc. but is referred to as article within the code. """,
    tags=['article_management'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def create_article(body: Article = None):
    """
    Publish article
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/articles/latest',
    description=""" This endpoint allows the client to retrieve a list of articles. ordered by descending publish date.

It supports pagination, each page will contain 30 articles by default. """,
    tags=['article_management'],
)
def get_latest_articles(
    page: Optional[conint(ge=1)] = 1, per_page: Optional[conint(ge=1, le=1000)] = 30
):
    """
    Published articles sorted by published date
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/articles/me',
    description=""" This endpoint allows the client to retrieve a list of published articles on behalf of an authenticated user.

"Articles" are all the posts that users create on DEV that typically show up in the feed. They can be a blog post, a discussion question, a help thread etc. but is referred to as article within the code.

Published articles will be in reverse chronological publication order.

It will return published articles with pagination. By default a page will contain 30 articles. """,
    tags=['user_information_retrieval', 'article_management'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def get_user_articles(
    page: Optional[conint(ge=1)] = 1, per_page: Optional[conint(ge=1, le=1000)] = 30
):
    """
    User's articles
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/articles/me/all',
    description=""" This endpoint allows the client to retrieve a list of all articles on behalf of an authenticated user.

"Articles" are all the posts that users create on DEV that typically show up in the feed. They can be a blog post, a discussion question, a help thread etc. but is referred to as article within the code.

It will return both published and unpublished articles with pagination.

Unpublished articles will be at the top of the list in reverse chronological creation order. Published articles will follow in reverse chronological publication order.

By default a page will contain 30 articles. """,
    tags=['article_management', 'user_information_retrieval'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def get_user_all_articles(
    page: Optional[conint(ge=1)] = 1, per_page: Optional[conint(ge=1, le=1000)] = 30
):
    """
    User's all articles
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/articles/me/published',
    description=""" This endpoint allows the client to retrieve a list of published articles on behalf of an authenticated user.

"Articles" are all the posts that users create on DEV that typically show up in the feed. They can be a blog post, a discussion question, a help thread etc. but is referred to as article within the code.

Published articles will be in reverse chronological publication order.

It will return published articles with pagination. By default a page will contain 30 articles. """,
    tags=['article_management', 'user_information_retrieval'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def get_user_published_articles(
    page: Optional[conint(ge=1)] = 1, per_page: Optional[conint(ge=1, le=1000)] = 30
):
    """
    User's published articles
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/articles/me/unpublished',
    description=""" This endpoint allows the client to retrieve a list of unpublished articles on behalf of an authenticated user.

"Articles" are all the posts that users create on DEV that typically show up in the feed. They can be a blog post, a discussion question, a help thread etc. but is referred to as article within the code.

Unpublished articles will be in reverse chronological creation order.

It will return unpublished articles with pagination. By default a page will contain 30 articles. """,
    tags=['article_management', 'user_management'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def get_user_unpublished_articles(
    page: Optional[conint(ge=1)] = 1, per_page: Optional[conint(ge=1, le=1000)] = 30
):
    """
    User's unpublished articles
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/articles/{id}',
    description=""" This endpoint allows the client to retrieve a single published article given its `id`. """,
    tags=['article_management'],
)
def get_article_by_id(id: int):
    """
    Published article by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/articles/{id}',
    description=""" This endpoint allows the client to update an existing article.

"Articles" are all the posts that users create on DEV that typically show up in the feed. They can be a blog post, a discussion question, a help thread etc. but is referred to as article within the code. """,
    tags=['article_management'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def update_article(id: conint(ge=1), body: Article = None):
    """
    Update an article by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/articles/{id}/unpublish',
    description=""" This endpoint allows the client to unpublish an article.

The user associated with the API key must have any 'admin' or 'moderator' role.

The article will be unpublished and will no longer be visible to the public. It will remain
in the database and will set back to draft status on the author's posts dashboard. Any
notifications associated with the article will be deleted. Any comments on the article
will remain. """,
    tags=['article_management', 'user_account_moderation'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def unpublish_article(id: conint(ge=1), note: Optional[str] = None):
    """
    Unpublish an article
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/articles/{username}/{slug}',
    description=""" This endpoint allows the client to retrieve a single published article given its `path`. """,
    tags=['article_management'],
)
def get_article_by_path(username: str, slug: str = ...):
    """
    Published article by path
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/comments',
    description=""" This endpoint allows the client to retrieve all comments belonging to an article or podcast episode as threaded conversations.

It will return the all top level comments with their nested comments as threads. See the format specification for further details. """,
    tags=['comment_management'],
)
def get_comments_by_article_id(a_id: Optional[str] = None, p_id: Optional[str] = None):
    """
    Comments
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/comments/{id}',
    description=""" This endpoint allows the client to retrieve a comment as well as his descendants comments.

  It will return the required comment (the root) with its nested descendants as a thread.

  See the format specification for further details. """,
    tags=['comment_management'],
)
def get_comment_by_id(id: int):
    """
    Comment by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/display_ads',
    description=""" This endpoint allows the client to retrieve a list of all display ads. """,
    tags=['display_ad_management'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def get_api_display_ads():
    """
    display ads
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/display_ads',
    description=""" This endpoint allows the client to create a new display ad. """,
    tags=['display_ad_management'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def post_api_display_ads(body: ApiDisplayAdsPostRequest = None):
    """
    display ads
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/display_ads/{id}',
    description=""" This endpoint allows the client to retrieve a single display ad, via its id. """,
    tags=['display_ad_management'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def get_api_display_ads__id(id: conint(ge=1)):
    """
    display ad
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/display_ads/{id}',
    description=""" This endpoint allows the client to update the attributes of a single display ad, via its id. """,
    tags=['display_ad_management'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def put_api_display_ads__id(id: conint(ge=1), body: ApiDisplayAdsIdPutRequest = None):
    """
    display ads
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/display_ads/{id}/unpublish',
    description=""" This endpoint allows the client to remove a display ad from rotation by un-publishing it. """,
    tags=['article_management', 'user_account_moderation'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def put_api_display_ads__id_unpublish(id: conint(ge=1)):
    """
    unpublish
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/followers/users',
    description=""" This endpoint allows the client to retrieve a list of the followers they have.
        "Followers" are users that are following other users on the website.
        It supports pagination, each page will contain 80 followers by default. """,
    tags=['user_management', 'user_information_retrieval'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def get_followers(
    page: Optional[conint(ge=1)] = 1,
    per_page: Optional[conint(ge=1, le=1000)] = 30,
    sort: Optional[str] = None,
):
    """
    Followers
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/follows/tags',
    description=""" This endpoint allows the client to retrieve a list of the tags they follow. """,
    tags=['user_management', 'user_information_retrieval'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def get_followed_tags():
    """
    Followed Tags
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/organizations/{username}',
    description=""" This endpoint allows the client to retrieve a single organization by their username """,
    tags=['organization_management', 'user_management'],
)
def get_organization(username: str):
    """
    An organization
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/organizations/{username}/articles',
    description=""" This endpoint allows the client to retrieve a list of Articles belonging to the organization

It supports pagination, each page will contain `30` users by default. """,
    tags=['organization_management', 'article_management'],
)
def get_org_articles(
    username: str,
    page: Optional[conint(ge=1)] = 1,
    per_page: Optional[conint(ge=1, le=1000)] = 30,
):
    """
    Organization's Articles
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/organizations/{username}/users',
    description=""" This endpoint allows the client to retrieve a list of users belonging to the organization

It supports pagination, each page will contain `30` users by default. """,
    tags=['user_management', 'organization_management', 'user_information_retrieval'],
)
def get_org_users(
    username: str,
    page: Optional[conint(ge=1)] = 1,
    per_page: Optional[conint(ge=1, le=1000)] = 30,
):
    """
    Organization's users
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/pages',
    description=""" This endpoint allows the client to retrieve details for all Page objects. """,
    tags=['page_management'],
)
def get_api_pages():
    """
    show details for all pages
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/pages',
    description=""" This endpoint allows the client to create a new page. """,
    tags=['page_management'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def post_api_pages(body: ApiPagesPostRequest = None):
    """
    pages
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/pages/{id}',
    description=""" This endpoint allows the client to delete a single Page object, specified by ID. """,
    tags=['page_management'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def delete_api_pages__id(id: conint(ge=1)):
    """
    remove a page
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/pages/{id}',
    description=""" This endpoint allows the client to retrieve details for a single Page object, specified by ID. """,
    tags=['page_management'],
)
def get_api_pages__id(id: conint(ge=1)):
    """
    show details for a page
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/pages/{id}',
    description=""" This endpoint allows the client to retrieve details for a single Page object, specified by ID. """,
    tags=['page_management'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def put_api_pages__id(id: conint(ge=1), body: Page = None):
    """
    update details for a page
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/podcast_episodes',
    description=""" This endpoint allows the client to retrieve a list of podcast episodes.
        "Podcast episodes" are episodes belonging to podcasts.
        It will only return active (reachable) podcast episodes that belong to published podcasts available on the platform, ordered by descending publication date.
        It supports pagination, each page will contain 30 articles by default. """,
    tags=['podcast_management'],
)
def get_podcast_episodes(
    page: Optional[conint(ge=1)] = 1,
    per_page: Optional[conint(ge=1, le=1000)] = 30,
    username: Optional[str] = None,
):
    """
    Podcast Episodes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/profile_images/{username}',
    description=""" This endpoint allows the client to retrieve a user or organization profile image information by its
        corresponding username. """,
    tags=['user_profile_management'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def get_profile_image(username: str):
    """
    A Users or organizations profile image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/reactions',
    description=""" This endpoint allows the client to create a reaction to a specified reactable (eg, Article, Comment, or User). For examples:
        * "Like"ing an Article will create a new "like" Reaction from the user for that Articles
        * "Like"ing that Article a second time will return the previous "like" """,
    tags=['user_activity_reactions'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def post_api_reactions(
    category: Category, reactable_id: int = ..., reactable_type: ReactableType = ...
):
    """
    create reaction
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/reactions/toggle',
    description=""" This endpoint allows the client to toggle the user's reaction to a specified reactable (eg, Article, Comment, or User). For examples:
        * "Like"ing an Article will create a new "like" Reaction from the user for that Articles
        * "Like"ing that Article a second time will remove the "like" from the user """,
    tags=['user_activity_reactions'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def post_api_reactions_toggle(
    category: Category, reactable_id: int = ..., reactable_type: ReactableType = ...
):
    """
    toggle reaction
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/readinglist',
    description=""" This endpoint allows the client to retrieve a list of articles that were saved to a Users readinglist.
        It supports pagination, each page will contain `30` articles by default """,
    tags=['user_reading_lists'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def get_readinglist(
    page: Optional[conint(ge=1)] = 1, per_page: Optional[conint(ge=1, le=1000)] = 30
):
    """
    Readinglist
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/tags',
    description=""" This endpoint allows the client to retrieve a list of tags that can be used to tag articles.

It will return tags ordered by popularity.

It supports pagination, each page will contain 10 tags by default. """,
    tags=['user_tags_management'],
)
def get_tags(
    page: Optional[conint(ge=1)] = 1, per_page: Optional[conint(ge=1, le=1000)] = 10
):
    """
    Tags
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/me',
    description=""" This endpoint allows the client to retrieve information about the authenticated user """,
    tags=['user_information_retrieval', 'user_management'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def get_user_me():
    """
    The authenticated user
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/{id}',
    description=""" This endpoint allows the client to retrieve a single user, either by id
or by the user's username.

For complete documentation, see the v0 API docs: https://developers.forem.com/api/v0#tag/users/operation/getUser """,
    tags=['user_management', 'user_information_retrieval', 'user_profile_management'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def get_user(id: str):
    """
    A User
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/users/{id}/suspend',
    description=""" This endpoint allows the client to suspend a user.

The user associated with the API key must have any 'admin' or 'moderator' role.

This specified user will be assigned the 'suspended' role. Suspending a user will stop the
user from posting new posts and comments. It doesn't delete any of the user's content, just
prevents them from creating new content while suspended. Users are not notified of their suspension
in the UI, so if you want them to know about this, you must notify them. """,
    tags=['user_management', 'user_account_moderation'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def suspend_user(id: conint(ge=1)):
    """
    Suspend a User
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/users/{id}/unpublish',
    description=""" This endpoint allows the client to unpublish all of the articles and
comments created by a user.

The user associated with the API key must have any 'admin' or 'moderator' role.

This specified user's articles and comments will be unpublished and will no longer be
visible to the public. They will remain in the database and will set back to draft status
on the specified user's  dashboard. Any notifications associated with the specified user's
articles and comments will be deleted.

Note this endpoint unpublishes articles and comments asychronously: it will return a 204 NO CONTENT
status code immediately, but the articles and comments will not be unpublished until the
request is completed on the server. """,
    tags=['article_management', 'comment_management', 'user_account_moderation'],
    security=[
        APIKeyHeader(name="api-key"),
    ],
)
def unpublish_user(id: conint(ge=1)):
    """
    Unpublish a User's Articles and Comments
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/videos',
    description=""" This endpoint allows the client to retrieve a list of articles that are uploaded with a video.

It will only return published video articles ordered by descending popularity.

It supports pagination, each page will contain 24 articles by default. """,
    tags=['article_management', 'video_article_retrieval'],
)
def videos(
    page: Optional[conint(ge=1)] = 1, per_page: Optional[conint(ge=1, le=1000)] = 24
):
    """
    Articles with a video
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
