# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:30:38+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, RootModel


class Article1(BaseModel):
    body_markdown: Optional[str] = None
    canonical_url: Optional[str] = None
    description: Optional[str] = None
    main_image: Optional[str] = None
    organization_id: Optional[int] = None
    published: Optional[bool] = False
    series: Optional[str] = None
    tags: Optional[str] = None
    title: Optional[str] = None


class Article(BaseModel):
    article: Optional[Article1] = None


class ArticleFlareTag(BaseModel):
    bg_color_hex: Optional[str] = Field(
        None, description='Background color (hexadecimal)'
    )
    name: Optional[str] = None
    text_color_hex: Optional[str] = Field(None, description='Text color (hexadecimal)')


class Comment(BaseModel):
    created_at: Optional[datetime] = None
    id_code: Optional[str] = None
    image_url: Optional[str] = Field(None, description='Podcast image url')
    type_of: Optional[str] = None


class FollowedTag(BaseModel):
    id: int = Field(..., description='Tag id')
    name: str
    points: float


class Organization(BaseModel):
    github_username: Optional[str] = None
    joined_at: Optional[str] = None
    location: Optional[str] = None
    name: Optional[str] = None
    story: Optional[str] = None
    summary: Optional[str] = None
    tag_line: Optional[str] = None
    tech_stack: Optional[str] = None
    twitter_username: Optional[str] = None
    type_of: Optional[str] = None
    url: Optional[str] = None
    username: Optional[str] = None


class Template(Enum):
    contained = 'contained'
    full_within_layout = 'full_within_layout'
    nav_bar_included = 'nav_bar_included'
    json = 'json'


class Page(BaseModel):
    body_json: Optional[str] = Field(None, description='For JSON pages, the JSON body')
    body_markdown: Optional[str] = Field(
        None, description='The text (in markdown) of the ad (required)'
    )
    description: str = Field(
        ..., description='For internal use, helps similar pages from one another'
    )
    is_top_level_path: Optional[bool] = Field(
        None,
        description="If true, the page is available at '/{slug}' instead of '/page/{slug}', use with caution",
    )
    slug: str = Field(
        ...,
        description='Used to link to this page in URLs, must be unique and URL-safe',
    )
    social_image: Optional[Dict[str, Any]] = None
    template: Template = Field(
        ..., description='Controls what kind of layout the page is rendered in'
    )
    title: str = Field(..., description='Title of the page')


class ProfileImage(BaseModel):
    image_of: Optional[str] = Field(
        None,
        description='Determines the type of the profile image owner (user or organization)',
    )
    profile_image: Optional[str] = Field(None, description='Profile image (640x640)')
    profile_image_90: Optional[str] = Field(None, description='Profile image (90x90)')
    type_of: Optional[str] = Field(None, description='Return profile_image')


class SharedOrganization(BaseModel):
    name: Optional[str] = None
    profile_image: Optional[str] = Field(None, description='Profile image (640x640)')
    profile_image_90: Optional[str] = Field(None, description='Profile image (90x90)')
    slug: Optional[str] = None
    username: Optional[str] = None


class SharedPodcast(BaseModel):
    image_url: Optional[str] = Field(None, description='Podcast image url')
    slug: Optional[str] = None
    title: Optional[str] = None


class SharedUser(BaseModel):
    github_username: Optional[str] = None
    name: Optional[str] = None
    profile_image: Optional[str] = Field(None, description='Profile image (640x640)')
    profile_image_90: Optional[str] = Field(None, description='Profile image (90x90)')
    twitter_username: Optional[str] = None
    username: Optional[str] = None
    website_url: Optional[str] = None


class Tag(BaseModel):
    bg_color_hex: Optional[str] = None
    id: Optional[int] = Field(None, description='Tag id')
    name: Optional[str] = None
    text_color_hex: Optional[str] = None


class User(BaseModel):
    github_username: Optional[str] = None
    id: Optional[int] = None
    joined_at: Optional[str] = None
    location: Optional[str] = None
    name: Optional[str] = None
    profile_image: Optional[str] = None
    summary: Optional[str] = None
    twitter_username: Optional[str] = None
    type_of: Optional[str] = None
    username: Optional[str] = None
    website_url: Optional[str] = None


class UserInviteParam(BaseModel):
    email: Optional[str] = None
    name: Optional[str] = None


class User1(BaseModel):
    name: Optional[str] = None


class VideoArticle(BaseModel):
    cloudinary_video_url: Optional[str] = None
    id: Optional[int] = None
    path: Optional[str] = None
    title: Optional[str] = None
    type_of: Optional[str] = None
    user: Optional[User1] = Field(None, description='Author of the article')
    user_id: Optional[int] = None
    video_duration_in_minutes: Optional[str] = None
    video_source_url: Optional[str] = None


class State(Enum):
    fresh = 'fresh'
    rising = 'rising'
    all = 'all'


class ApiArticlesIdGetResponse1(BaseModel):
    pass


class ApiArticlesUsernameSlugGetResponse1(BaseModel):
    pass


class ApiCommentsGetResponse(RootModel[List[Comment]]):
    root: List[Comment]


class DisplayTo(Enum):
    all = 'all'
    logged_in = 'logged_in'
    logged_out = 'logged_out'


class PlacementArea(Enum):
    sidebar_left = 'sidebar_left'
    sidebar_left_2 = 'sidebar_left_2'
    sidebar_right = 'sidebar_right'
    post_sidebar = 'post_sidebar'
    post_comments = 'post_comments'


class TypeOf(Enum):
    in_house = 'in_house'
    community = 'community'
    external = 'external'


class ApiDisplayAdsPostRequest(BaseModel):
    approved: Optional[bool] = Field(
        None, description='Ad must be both published and approved to be in rotation'
    )
    body_markdown: str = Field(
        ..., description='The text (in markdown) of the ad (required)'
    )
    creator_id: Optional[int] = Field(
        None, description='Identifies the user who created the ad.'
    )
    display_to: Optional[DisplayTo] = Field(
        'all', description='Potentially limits visitors to whom the ad is visible'
    )
    name: str = Field(
        ..., description='For internal use, helps distinguish ads from one another'
    )
    organization_id: Optional[int] = Field(
        None, description='Identifies the organization to which the ad belongs'
    )
    placement_area: PlacementArea = Field(
        ..., description='Identifies which area of site layout the ad can appear in'
    )
    published: Optional[bool] = Field(
        None, description='Ad must be both published and approved to be in rotation'
    )
    tag_list: Optional[str] = Field(
        None,
        description='Tags on which this ad can be displayed (blank is all/any tags)',
    )
    type_of: Optional[TypeOf] = Field(
        'in_house',
        description="Types of the billboards:\nin_house (created by admins),\ncommunity (created by an entity, appears on entity's content),\nexternal ( created by an entity, or a non-entity, can appear everywhere)\n",
    )


class ApiDisplayAdsIdPutRequest(BaseModel):
    approved: Optional[bool] = Field(
        None, description='Ad must be both published and approved to be in rotation'
    )
    body_markdown: str = Field(
        ..., description='The text (in markdown) of the ad (required)'
    )
    creator_id: Optional[int] = Field(
        None, description='Identifies the user who created the ad.'
    )
    display_to: Optional[DisplayTo] = Field(
        'all', description='Potentially limits visitors to whom the ad is visible'
    )
    name: str = Field(
        ..., description='For internal use, helps distinguish ads from one another'
    )
    organization_id: Optional[int] = Field(
        None,
        description="Identifies the organization to which the ad belongs, required for 'community' type ads",
    )
    placement_area: PlacementArea = Field(
        ..., description='Identifies which area of site layout the ad can appear in'
    )
    published: Optional[bool] = Field(
        None, description='Ad must be both published and approved to be in rotation'
    )
    tag_list: Optional[str] = Field(
        None,
        description='Tags on which this ad can be displayed (blank is all/any tags)',
    )


class ApiFollowersUsersGetResponseItem(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = Field(None, description="The follower's name")
    path: Optional[str] = Field(None, description="A path to the follower's profile")
    profile_image: Optional[str] = Field(None, description='Profile image (640x640)')
    type_of: Optional[str] = Field(None, description='user_follower by default')
    user_id: Optional[int] = Field(None, description="The follower's user id")


class ApiFollowersUsersGetResponse(RootModel[List[ApiFollowersUsersGetResponseItem]]):
    root: List[ApiFollowersUsersGetResponseItem]


class ApiFollowsTagsGetResponse(RootModel[List[FollowedTag]]):
    root: List[FollowedTag]


class ApiOrganizationsUsernameGetResponse1(BaseModel):
    pass


class ApiOrganizationsUsernameGetResponse(
    RootModel[Union[List[Organization], ApiOrganizationsUsernameGetResponse1]]
):
    root: Union[List[Organization], ApiOrganizationsUsernameGetResponse1]


class ApiOrganizationsUsernameUsersGetResponse(RootModel[List[User]]):
    root: List[User]


class ApiPagesGetResponse(RootModel[List[Page]]):
    root: List[Page]


class ApiPagesPostRequest(BaseModel):
    body_json: Optional[str] = Field(None, description='For JSON pages, the JSON body')
    body_markdown: Optional[str] = Field(
        None, description='The text (in markdown) of the ad (required)'
    )
    description: Optional[str] = Field(
        None, description='For internal use, helps similar pages from one another'
    )
    is_top_level_path: Optional[bool] = Field(
        None,
        description="If true, the page is available at '/{slug}' instead of '/page/{slug}', use with caution",
    )
    slug: Optional[str] = Field(
        None,
        description='Used to link to this page in URLs, must be unique and URL-safe',
    )
    template: Optional[Template] = Field(
        'contained', description='Controls what kind of layout the page is rendered in'
    )
    title: Optional[str] = Field(None, description='Title of the page')


class ApiProfileImagesUsernameGetResponse1(BaseModel):
    pass


class ApiProfileImagesUsernameGetResponse(
    RootModel[Union[List[ProfileImage], ApiProfileImagesUsernameGetResponse1]]
):
    root: Union[List[ProfileImage], ApiProfileImagesUsernameGetResponse1]


class Category(Enum):
    like = 'like'
    unicorn = 'unicorn'
    exploding_head = 'exploding_head'
    raised_hands = 'raised_hands'
    fire = 'fire'


class ReactableType(Enum):
    Comment = 'Comment'
    Article = 'Article'
    User = 'User'


class ApiTagsGetResponse(RootModel[List[Tag]]):
    root: List[Tag]


class ApiUsersMeGetResponse1(BaseModel):
    pass


class ApiUsersMeGetResponse(RootModel[Union[List[User], ApiUsersMeGetResponse1]]):
    root: Union[List[User], ApiUsersMeGetResponse1]


class ApiUsersIdGetResponse1(BaseModel):
    pass


class ApiUsersIdGetResponse(RootModel[Union[List[User], ApiUsersIdGetResponse1]]):
    root: Union[List[User], ApiUsersIdGetResponse1]


class ApiVideosGetResponse(RootModel[List[VideoArticle]]):
    root: List[VideoArticle]


class ArticleIndex(BaseModel):
    canonical_url: str
    cover_image: str
    created_at: datetime
    crossposted_at: datetime
    description: str
    edited_at: datetime
    flare_tag: Optional[ArticleFlareTag] = None
    id: int
    last_comment_at: datetime
    organization: Optional[SharedOrganization] = None
    path: Path
    positive_reactions_count: int
    public_reactions_count: int
    published_at: datetime
    published_timestamp: datetime = Field(
        ..., description='Crossposting or published date time'
    )
    readable_publish_date: str
    reading_time_minutes: int = Field(..., description='Reading time, in minutes')
    slug: str
    social_image: str
    tag_list: List[str]
    tags: str
    title: str
    type_of: str
    url: str
    user: SharedUser


class PodcastEpisodeIndex(BaseModel):
    class_name: str
    id: int
    image_url: str = Field(
        ..., description='Podcast episode image url or podcast image url'
    )
    path: Path
    podcast: SharedPodcast
    title: str
    type_of: str


class ApiArticlesGetResponse(RootModel[List[ArticleIndex]]):
    root: List[ArticleIndex]


class ApiArticlesLatestGetResponse(RootModel[List[ArticleIndex]]):
    root: List[ArticleIndex]


class ApiArticlesMeGetResponse(RootModel[List[ArticleIndex]]):
    root: List[ArticleIndex]


class ApiArticlesMeAllGetResponse(RootModel[List[ArticleIndex]]):
    root: List[ArticleIndex]


class ApiArticlesMePublishedGetResponse(RootModel[List[ArticleIndex]]):
    root: List[ArticleIndex]


class ApiArticlesMeUnpublishedGetResponse(RootModel[List[ArticleIndex]]):
    root: List[ArticleIndex]


class ApiArticlesIdGetResponse(
    RootModel[Union[List[ArticleIndex], ApiArticlesIdGetResponse1]]
):
    root: Union[List[ArticleIndex], ApiArticlesIdGetResponse1]


class ApiArticlesUsernameSlugGetResponse(
    RootModel[Union[List[ArticleIndex], ApiArticlesUsernameSlugGetResponse1]]
):
    root: Union[List[ArticleIndex], ApiArticlesUsernameSlugGetResponse1]


class ApiOrganizationsUsernameArticlesGetResponse(RootModel[List[ArticleIndex]]):
    root: List[ArticleIndex]


class ApiPodcastEpisodesGetResponse(RootModel[List[PodcastEpisodeIndex]]):
    root: List[PodcastEpisodeIndex]


class ApiReadinglistGetResponse(RootModel[List[ArticleIndex]]):
    root: List[ArticleIndex]
